### ISSUE TITLE
Clarification topology and batchsize

### ISSUE THREAD

**Issue by JohannesKaminski** [yoch/sparse-som#4]
Hi Yoch,
first of all, thanks for this tool!

I've a question regarding the three topology modes available. I understand that HEXA must be the well known hexagonal grid layout, but which one is the classic 4-neighbour grid, and what kind of map layout is the other one representing? My understanding would be, that both CIRC and RECT have a normal grid layout, but CIRC would only consider (0, +/-1) and (+/-1, 0) as direct neighbours and (+/-1,+/-1) as second neighbours since they have a manhattan distance of 2, while RECT also considers the diagonal neighbours (+/-1,+/-1) as first neighbours. Is that correct?
Also could you elaborate on when the map update is performed? Is it done after passing the whole dataset once or after a certain k-percent of the dataset?
Thanks!

**Comment by yoch** [comment]
Hi

You're right, both CIRC and RECT use the same regular topology, but CIRC uses euclidean distance end RECT uses manhattan distance.

Regarding to the update frequency, it's depend which version you are considering. 
- For `Som` the update is performed at each data presented to the network, there is no concept of "epoch". 
- For `BSom`, the update is performed after evaluating the whole dataset, which is one epoch.

There are also intermediate approaches in the literature, but I've not implemented them.
